<<<<<<< HEAD
# Generated by Django 2.0.13 on 2019-05-21 00:57
=======
# Generated by Django 2.1.2 on 2019-05-21 00:56
>>>>>>> 8a8812c4a28c668a36d8917e493d0829141fc1fe

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perris', '0004_auto_20181030_0128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perro',
        ),
    ]
