# Generated by Django 2.0.13 on 2019-05-21 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perris', '0004_auto_20181030_0128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perro',
        ),
    ]
